version: 2
jobs:
  build:
    docker:
      - image: {{ cookiecutter.ci_docker_image}} 
    working_directory: /usr/src/{{ cookiecutter.repo_name }}
    steps:
      - checkout
      - run: mkdir -p test_output/pytest test_output/flake8 test_output/coverage test_output/mypy
      - run: pip install .[dev]
      - run: make test-xml
      - run: make typecheck-xml
      - run: make lint-xml
      - store_artifacts:
          path: test_output/coverage
          destination: reports
      - store_test_results:
          path: test_output/
