language: python

python:
  - "3.4"
  - "2.7"
  - "pypy"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - libatlas-base-dev
    - gfortran

before_install:
  - wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz
  - tar -xvf nlopt-2.4.2.tar.gz
  - cd nlopt-2.4.2
  - PYTHON=$(which python) ./configure --prefix=$(dirname $(dirname $(which python))) --enable-shared
  - make
  - make install

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - py.test --cov=./

cache:
  - apt
  - pip
  - directories:
    - $HOME/.cache/pip

after_success:
  - codecov
